# Generated by Django 3.0.3 on 2020-02-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('subtitle_name', models.TextField()),
                ('tel', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('facebook', models.TextField(blank=True, null=True)),
                ('instagram', models.TextField(blank=True, null=True)),
                ('about', models.TextField()),
                ('short_about', models.CharField(max_length=140)),
                ('building_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('logo', models.ImageField(default='image/logo-default.jpg', upload_to='images/')),
                ('src_googlemap', models.TextField(blank=True, null=True)),
                ('schedule_monday_friday', models.TextField()),
                ('schedule_saturday', models.TextField()),
                ('schedule_sunday', models.TextField()),
                ('schedule_holidays', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('category', models.TextField(choices=[('', ''), ('office', 'office'), ('school', 'school'), ('cel_accessory', 'cel_accessory'), ('desktop', 'desktop'), ('Laptop', 'Laptop'), ('pc_accessory', 'pc_accessory'), ('pc_components', 'pc_components')], default='')),
                ('img', models.ImageField(default='images/default.png', upload_to='images/products/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.ImageField(default='images/default.png', upload_to='images/services/')),
            ],
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('slide_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('img', models.ImageField(default='images/default-slide.jpg', upload_to='images/slides/')),
            ],
        ),
    ]
