# Generated by Django 3.0.3 on 2020-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesswebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='schedule_holidays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='schedule_monday_friday',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='schedule_saturday',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='schedule_sunday',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slides',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
