# Generated by Django 3.0.3 on 2020-02-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesswebsite', '0002_auto_20200218_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
